#!/usr/bin/env python

Import( 'env' )

env.spaceecs_sources = []

env.add_source_files( env.spaceecs_sources, "*.cpp" )

lib = env.add_library("spaceecs", env.spaceecs_sources)
env.Prepend(LIBS=[lib])